version: '3.8'

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: ynmatveev/foodgram:latest
    restart: always
    volumes:
      - static_value:/code/static/
      - media_value:/code/media/

    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - "80:80"

    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - web-root:/var/html/

    depends_on:
      - web


  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/html/

    depends_on:
      - nginx

    command: certonly --webroot --webroot-path=/var/html --email yptester@yandex.ru --agree-tos --no-eff-email --force-renewal --staging -d foodgram.ynm-project.online  -d www.foodgram.ynm-project.online

volumes:
  postgres_data:
  static_value:
  media_value:
  certbot-etc:
  certbot-var:
  web-root: