# Generated by Django 3.2.2 on 2021-05-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_list', '0002_alter_shoppingcart_shopping_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='shopping_list',
            field=models.JSONField(default=list, verbose_name='Список рецептов'),
        ),
    ]
