# Generated by Django 3.2.2 on 2021-05-23 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import recipes.models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Name')),
                ('units', models.CharField(max_length=10, verbose_name='Units of measurements')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecipeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_authors', to=settings.AUTH_USER_MODEL, verbose_name='Subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Recipe Title')),
                ('image', stdimage.models.StdImageField(upload_to='recipes/', verbose_name='Photo of the dish')),
                ('description', models.TextField(verbose_name='Recipe Description')),
                ('tags', multiselectfield.db.fields.MultiSelectField(choices=[('завтрак', 'завтрак'), ('обед', 'обед'), ('ужин', 'ужин')], default='завтрак', max_length=17, verbose_name='Tags')),
                ('cooking_time', models.PositiveIntegerField(verbose_name='Cooking time, minutes')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Published Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('author', models.ForeignKey(on_delete=models.SET(recipes.models.get_abstract_user), related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Recipe Author')),
                ('ingredients', models.ManyToManyField(related_name='recipes', through='recipes.IngredientRecipeMap', to='recipes.Ingredient', verbose_name='Required ingredients')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='ingredientrecipemap',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_ingredients', to='recipes.recipe'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chooser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Chooser')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipe', verbose_name='Favorite recipe')),
            ],
        ),
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.UniqueConstraint(fields=('subscriber', 'author'), name='unique_subscribe'),
        ),
        migrations.AddConstraint(
            model_name='ingredientrecipemap',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('chooser', 'recipe'), name='unique_favorites'),
        ),
    ]
