# Generated by Django 3.2.2 on 2021-05-25 21:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20210525_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipemap',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
