# Generated by Django 3.2.2 on 2021-05-09 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recipes.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientRecipeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=60, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='units',
            field=models.CharField(max_length=10, verbose_name='Units of measurements'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Recipe Title')),
                ('image', stdimage.models.StdImageField(upload_to='recipes/')),
                ('description', models.TextField()),
                ('tag', models.TextField(choices=[('завтрак', 'завтрак'), ('обед', 'обед'), ('ужин', 'ужин')], verbose_name='Tags')),
                ('cooking_time', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('author', models.ForeignKey(on_delete=models.SET(recipes.models.get_abstract_user), related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Recipe Author')),
                ('ingredients', models.ManyToManyField(through='recipes.IngredientRecipeMap', to='recipes.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='ingredientrecipemap',
            name='ingridient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='recipes.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientrecipemap',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
