# Generated by Django 3.2.2 on 2021-05-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210509_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipemap',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
