# Generated by Django 3.2.2 on 2021-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_rename_ingridient_ingredientrecipemap_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientRecipeMap', to='recipes.Ingredient'),
        ),
    ]
