# Generated by Django 3.2.2 on 2021-05-09 16:46

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=stdimage.models.JPEGField(upload_to='recipes/'),
        ),
    ]
