# Generated by Django 3.2.2 on 2021-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_favorite_recipe'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('chooser', 'recipe'), name='unique_favorites'),
        ),
    ]
