# Generated by Django 3.2.2 on 2021-05-13 19:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0019_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('затрак', 'завтрак'), ('обед', 'обед'), ('ужин', 'ужин')], default='затрак', max_length=16, verbose_name='Tags'),
        ),
    ]
