# Generated by Django 3.2.2 on 2021-05-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='ingredientrecipemap',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_ingredients', to='recipes.recipe'),
        ),
    ]
